### ISSUE TITLE
the md5 for x64b seems to be wrong.

### ISSUE THREAD

**Issue by aabbey33** [Scarsz/GTAHash#1]
I noticed it would always delete the same file (x64b) whenever I verified. So i decided to check the online posted md5 (70af24cd4fe2c8ee58edb902f018a558) and yours and it seems to be different. I just ran a check with a new copy I compiled with the new md5 and it verified.

**Comment by Scarsz** [comment]
Hash list is a month old, submit a pull request with the new hashes

**Comment by Scarsz** [comment]
Did it myself

https://github.com/Scarsz/GTA5-MD5-Checker/commit/e8a9d42904f3d9f90d5552539310c0132a8f8f1e
